{% set name = "itsdangerous" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ItsDangerous-{{ version }}.tar.gz
  sha256: a7de3201740a857380421ef286166134e10fe58846bcefbc9d6424a69a0b99ec

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - itsdangerous

about:
  home: https://github.com/pallets/itsdangerous
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Various helpers to pass trusted data to untrusted environments.
  description: |
    Internally itsdangerous uses HMAC and SHA1 for signing data and bases the
    implementation on the Django signing module.  It also however supports JSON Web
    Signatures (JWS).
  doc_url: http://pythonhosted.org/itsdangerous
  dev_url: https://github.com/pallets/itsdangerous
  doc_source_url: https://github.com/pallets/itsdangerous/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - goanpeca
