travis:
  secure:
    BINSTAR_TOKEN: kz2a0KRdvcLSnG70YLF8P7uO80IaRl/QwIiJYrJhYB4iVWsK1ttAccQ3prA8HnbNw1a/P6FXV9SZ9MZOtlvqd0YTIqYWLOMsSMM1KP81bRCFcrFEW16zv0GFnc5Y5C/pv5l4KmfUXF8nmq8fXwZtKGpHDEvTFs/pkrwRAysOLo7MIapy9JvQXTqiW9CWL9XRDVnUIdVf8g4TvjhKUeRN6r53JLSFKYTzV8/l7FgV3u+WwthpDzNEWRw0YP7bZOlq/TDG1ZWPmcJwN53gnZKb/N1h4+DOUrOeZxsIwcTuCUccC8PxKaE4DBcpcKYXj9+jz/cmv2dInuvKv7W4vlkyeWU+MO2nP29AeB24ckp261cwmEQHUF0ujHkmRjkR9YRIkfJ37vgKvwkBgVkNKoH5C5w9svPMLLyZZrZbXAYKOrqBj6bKNgHG9P1sIt/3roGNI50jZ3M4Id3ChDvsQkHh1KAUB6IXSewjZ1WxoD+k/ig9woVz5pom3xcyfvMjshPDk5eDoF72Da13Rhy++8Tcp8KljNpQADGWjVxlPswtD2mWiBubAz8ctvVVue+A9NlHsh5Wz6yuKfgmVDlUCrlb88t1jYcvb9hb6GM2TN9jVs/7uJkrFrfdozEiakuAVIp9nkM+LiSBM+avyQj/Y0xfigNveiNxFwNZA4iKmBvher4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
