travis:
  secure:
    BINSTAR_TOKEN: WuqzOlVFwoTFhzyIVAuj/a0tmtwr5ziy3kGZfoRUa8+5K4Vf7B+hcNOO1rD8g7ZOS2sX2DT0L4XjPq8pRqcoul8p+hz2wEE/o42QVIGvqb99LS2oxPXVxfze5ch0qNQhpuIzmDB4aadaQc+wacO1xWxlgg90tk86bA62wOaMLW9TMvGCFwcwymi9ca2OsecwFSHKyPd0wtNTSaeWVYSxpz5lMP9r82V9KBGy0vmpQlwM/QsbRcxtq4ula8ug4jn5jFAPO1L/0LM7TsmxSrj9ExSnpcHCOg4aJYvyUqWRb3IK88gB0mLpOakN9ThDuHkxh/xD6Ck6SbRjUf4QHG3HTT8YQMO0D99cDMcGOCtJsf9f5o0YG5Gogyj4DfNDY5nEZyME2kvjpoVuWYnvp0ZK3OW3sZtij5wp+OMtorOYu7KOSY3NnFg9h+C4Jd8/qosknogx/7e6i579GW8wK09dyeg0iscMhvHrfs7QWv3KCNxc1xYsc+CoaM8xSbmua2CGOoWUVss5RguATGUTcf/4T6del7L+/DcY/ycRgAfiFVS9fyO3LCE58qqUAQ39YZk3GZ0kxh7vvkMpcCZo3J8AK9ijwnmUeAZZrwxRjmVdLeTMHvi9I1MA7dPeIb+WmTXJzkHA6TKaoiROca/TWyobJczOdT6pPsmEzmDsv/iW7QY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
