travis:
  secure:
    BINSTAR_TOKEN: Y05R09cpkM3/FaoDSIt4OU6fHKLOx1oZlfqq8cMbOr+mZiW3OJRfUGnVlqXekzshrafVMiDZY/dpEmZBRzFpo3k/iD9RGHSin/lFDQgWpAer4oxmJffeARzPxzohXaV0k3QA81NWwX7qPDaMKRV+zJknJVlFplnZ/xeNv4ARzaV4IePtgnSClIZa7e2pxRaW+WP1sIMMyTjVIj0lzHnPf5lJarzO1ukLGeyMpH2+Vn9i2T8X1dU09xuuBYGqWJXIEeuA9HLe94uJ6UwyCuPKGVAWNGBnfpmF328z8kSI/MkFgK/GBiaLGd+99qs9uh6griVhXf0hm0bzpE6NgfYi67zXt7+XcUKQ1QWiI90/XGX2bA9JTfz+EevN0unBYNPrlY0Cjr6wxxRCrDUBUY1I1onpGMKM9ecPTHOUBLxW56mlmT6sXN53h0hhSl8io8IW5m+qr/KuyTOcusBRbFtv2o1JZrXmzXNyO95PQbsz2ZaxJWlFNHpGJy3tbNAIlvoW42LAo+wWN5LhWs74ZYy8lU+MFEkKzcLHVVQwUbQ+M4gAAnwMqUGfIvjhGeRY88drj/g/ja9JX9q/ut0nC/HvjD9Ge7gVwwPLUgUsADfWaopO/KwyermM6CUa1unS0qZMDMXKO6wLJQXH7HEZXZW7MvrgzEonBmLryv7MUXkli18=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
